package com.example.cryptotest.models.remote.coinRates

data class Rates(
    val `611`: Double,
    val ABC: Double,
//    val ACP: Double,
//    val ACT: Double,
//    val ACT*: Double,
//    val ADA: Double,
//    val ADCN: Double,
//    val ADL: Double,
//    val ADX: Double,
    val ADZ: Double,
    val AE: Double,
    val AGI: Double,
    val AIB: Double,
    val AIDOC: Double,
    val AION: Double,
    val AIR: Double,
    val ALT: Double,
    val AMB: Double,
    val AMM: Double,
    val ANT: Double,
    val APC: Double,
    val APPC: Double,
    val ARC: Double,
    val ARCT: Double,
    val ARDR: Double,
    val ARK: Double,
    val ARN: Double,
    val ASAFE2: Double,
    val AST: Double,
    val ATB: Double,
    val ATM: Double,
    val AURS: Double,
    val AVAX: Double,
    val AVT: Double,
    val BAR: Double,
    val BASH: Double,
    val BAT: Double,
    val BAY: Double,
    val BBP: Double,
    val BCD: Double,
    val BCH: Double,
    val BCN: Double,
    val BCPT: Double,
    val BEE: Double,
    val BIO: Double,
    val BLC: Double,
    val BLOCK: Double,
    val BLU: Double,
    val BLZ: Double,
    val BMC: Double,
    val BNB: Double,
    val BNT: Double,
    val BOST: Double,
    val BQ: Double,
    val BQX: Double,
    val BRD: Double,
    val BRIT: Double,
    val BT1: Int,
    val BT2: Int,
    val BTC: Double,
//    val BTCA: Double,
//    val BTCS: Double,
//    val BTCZ: Double,
//    val BTG: Double,
//    val BTLC: Int,
//    val BTM: Double,
//    val BTM*: Double,
//    val BTQ: Double,
//    val BTS: Double,
    val BTX: Double,
    val BURST: Double,
    val CALC: Double,
    val CAS: Double,
    val CAT: Double,
    val CCRB: Double,
    val CDT: Double,
    val CESC: Double,
    val CHAT: Double,
//    val CJ: Double,
//    val CL: Double,
//    val CLD: Double,
//    val CLOAK: Int,
//    val CMT*: Double,
//    val CND: Double,
//    val CNX: Double,
//    val CPC: Double,
//    val CRAVE: Double,
//    val CRC: Double,
    val CRE: Double,
    val CRW: Double,
    val CTO: Double,
    val CTR: Double,
    val CVC: Double,
    val DAS: Double,
    val DASH: Double,
    val DAT: Double,
    val DATA: Int,
    val DBC: Double,
    val DBET: Double,
    val DCN: Double,
    val DCR: Double,
    val DCT: Double,
    val DEEP: Double,
    val DENT: Double,
    val DGB: Double,
    val DGD: Double,
    val DIM: Double,
    val DIME: Double,
    val DMD: Double,
    val DNT: Double,
    val DOGE: Double,
    val DRGN: Double,
    val DRZ: Int,
    val DSH: Double,
    val DTA: Double,
    val EC: Int,
    val EDG: Double,
    val EDO: Double,
    val EDR: Double,
    val EKO: Double,
    val ELA: Double,
    val ELF: Double,
    val EMC: Double,
    val EMGO: Double,
    val ENG: Double,
    val ENJ: Double,
    val EOS: Double,
    val ERT: Double,
//    val ETC: Double,
//    val ETH: Double,
//    val ETN: Double,
//    val ETP: Double,
//    val ETT: Double,
//    val EVR: Double,
//    val EVX: Double,
//    val FCT: Double,
//    val FLP: Double,
//    val FOTA: Double,
//    val FRST: Double,
//    val FUEL: Double,
//    val FUN: Double,
//    val FUNC: Double,
//    val FUTC: Double,
//    val GAME: Double,
//    val GAS: Double,
//    val GBYTE: Double,
//    val GMX: Double,
//    val GNO: Double,
//    val GNT: Double,
//    val GNX: Double,
//    val GRC: Double,
//    val GRS: Int,
//    val GRWI: Int,
//    val GTC: Double,
//    val GTO: Double,
//    val GUP: Double,
//    val GVT: Double,
//    val GXS: Double,
//    val HAC: Double,
//    val HNC: Int,
//    val HSR: Double,
//    val HST: Double,
//    val HVN: Double,
//    val ICN: Double,
//    val ICOS: Int,
//    val ICX: Double,
//    val IGNIS: Double,
//    val ILC: Double,
//    val INK: Double,
//    val INS: Double,
//    val INSN: Double,
//    val INT: Double,
//    val IOP: Double,
//    val IOST: Double,
//    val ITC: Double,
//    val KCS: Double,
//    val KICK: Double,
//    val KIN: Double,
//    val KLC: Double,
//    val KMD: Double,
//    val KNC: Double,
//    val KRB: Int,
//    val LA: Double,
//    val LEND: Double,
//    val LEO: Double,
//    val LINDA: Double,
//    val LINK: Double,
//    val LOC: Double,
//    val LOG: Double,
//    val LRC: Double,
//    val LSK: Double,
//    val LTC: Double,
//    val LUN: Double,
//    val LUX: Double,
//    val MAID: Double,
//    val MANA: Double,
//    val MCAP: Double,
//    val MCO: Double,
//    val MDA: Double,
//    val MDS: Double,
//    val MIOTA: Double,
//    val MKR: Double,
//    val MLN: Double,
//    val MNX: Double,
//    val MOD: Double,
//    val MOIN: Double,
//    val MONA: Double,
//    val MTL: Double,
//    val MTN*: Double,
//    val MTX: Double,
//    val NAS: Double,
//    val NAV: Double,
//    val NBT: Double,
//    val NDC: Double,
//    val NEBL: Double,
//    val NEO: Double,
//    val NEU: Double,
//    val NEWB: Double,
//    val NGC: Double,
//    val NKC: Double,
//    val NLC2: Double,
//    val NMC: Double,
//    val NMR: Double,
//    val NULS: Double,
//    val NVC: Int,
//    val NXT: Double,
//    val OAX: Double,
//    val OBITS: Double,
//    val OC: Double,
//    val OCN: Double,
//    val ODN: Double,
//    val OK: Double,
//    val OMG: Double,
//    val OMNI: Double,
//    val ORE: Int,
//    val ORME: Double,
//    val OST: Double,
//    val OTN: Int,
//    val OTX: Double,
//    val OXY: Double,
//    val PART: Double,
//    val PAY: Double,
//    val PBT: Double,
//    val PCS: Double,
//    val PIVX: Double,
//    val PIZZA: Double,
//    val PLBT: Int,
//    val PLR: Double,
//    val POE: Double,
//    val POLY: Double,
//    val POSW: Double,
//    val POWR: Double,
//    val PPC: Double,
//    val PPT: Double,
//    val PPY: Double,
//    val PRC: Double,
//    val PRES: Double,
//    val PRG: Double,
//    val PRL: Double,
//    val PRO: Double,
//    val PURA: Double,
//    val PUT: Int,
//    val QASH: Double,
//    val QAU: Int,
//    val QSP: Double,
//    val QTUM: Double,
//    val QUN: Double,
//    val R: Double,
//    val RBIES: Int,
//    val RCN: Double,
//    val RDD: Double,
//    val RDN: Int,
//    val RDN*: Double,
//    val REBL: Double,
//    val REE: Double,
//    val REP: Double,
//    val REQ: Double,
//    val REV: Double,
//    val RGC: Double,
//    val RHOC: Double,
//    val RIYA: Double,
//    val RKC: Int,
//    val RLC: Double,
//    val RPX: Double,
//    val RUFF: Double,
//    val SALT: Double,
//    val SAN: Double,
//    val SBC: Int,
//    val SC: Double,
//    val SENT: Double,
//    val SHIFT: Int,
//    val SIB: Double,
//    val SMART: Double,
//    val SMLY: Double,
//    val SMT*: Double,
//    val SNC: Double,
//    val SNGLS: Double,
//    val SNM: Double,
//    val SNT: Double,
//    val SPK: Double,
//    val SRN: Double,
//    val STEEM: Double,
//    val STK: Double,
//    val STORJ: Double,
//    val STRAT: Double,
//    val STU: Double,
//    val STX: Double,
//    val SUB: Double,
//    val SUR: Double,
//    val SWFTC: Double,
//    val SYS: Double,
//    val TAAS: Int,
//    val TESLA: Double,
//    val THC: Double,
//    val THETA: Double,
//    val THS: Double,
//    val TIO: Double,
//    val TKN: Int,
//    val TKY: Double,
//    val TNB: Double,
//    val TNT: Double,
//    val TOA: Double,
//    val TRC: Double,
//    val TRIG: Double,
//    val TRST: Double,
//    val TRUMP: Double,
//    val TRX: Double,
//    val UBQ: Double,
//    val UNO: Double,
//    val UNRC: Double,
//    val UQC: Int,
//    val USDT: Double,
//    val UTK: Double,
//    val UTT: Double,
//    val VEE: Double,
//    val VEN: Double,
//    val VERI: Double,
//    val VIA: Double,
//    val VIB: Double,
//    val VIBE: Double,
//    val VOISE: Double,
//    val VOX: Double,
//    val VRS: Double,
//    val VTC: Double,
//    val VUC: Double,
//    val WABI: Double,
//    val WAVES: Double,
//    val WAX: Double,
//    val WC: Double,
//    val WGR: Double,
//    val WINGS: Double,
//    val WLK: Double,
//    val WOP: Double,
//    val WPR: Double,
//    val WRC: Double,
//    val WTC: Double,
//    val XAUR: Double,
//    val XBP: Double,
//    val XBY: Double,
//    val XCP: Double,
//    val XCXT: Double,
//    val XDN: Double,
//    val XEM: Double,
//    val XGB: Double,
//    val XHI: Double,
//    val XID: Double,
//    val XLM: Double,
//    val XMR: Double,
//    val XNC: Double,
//    val XRB: Double,
//    val XRP: Double,
//    val XTO: Double,
//    val XTZ: Double,
//    val XUC: Double,
//    val XVG: Double,
//    val XZC: Double,
//    val YEE: Double,
//    val YOC: Double,
//    val YOYOW: Double,
//    val ZBC: Double,
//    val ZCL: Double,
//    val ZEC: Double,
//    val ZEN: Double,
//    val ZIL: Double,
//    val ZNY: Double,
//    val ZRX: Double,
//    val ZSC: Double
)