package com.example.cryptotest.models.remote.coinDetails

data class Crypto(
    val `611`: X611,
    val ABC: ABC,
    val ACP: ACP,
//    val ACT: ACT,
//    val ACT*: ACTX,
    val ADA: ADA,
    val ADCN: ADCN,
    val ADL: ADL,
    val ADX: ADX,
    val ADZ: ADZ,
    val AE: AE,
    val AGI: AGI,
    val AIB: AIB,
    val AIDOC: AIDOC,
    val AION: AION,
    val AIR: AIR,
    val ALT: ALT,
    val AMB: AMB,
    val AMM: AMM,
    val ANT: ANT,
    val APC: APC,
    val APPC: APPC,
    val ARC: ARC,
    val ARCT: ARCT,
    val ARDR: ARDR,
    val ARK: ARK,
    val ARN: ARN,
    val ASAFE2: ASAFE2,
    val AST: AST,
    val ATB: ATB,
    val ATM: ATM,
    val AURS: AURS,
    val AVAX: AVAX,
    val AVT: AVT,
    val BAR: BAR,
    val BASH: BASH,
    val BAT: BAT,
    val BAY: BAY,
    val BBP: BBP,
    val BCD: BCD,
    val BCH: BCH,
    val BCN: BCN,
    val BCPT: BCPT,
    val BEE: BEE,
    val BIO: BIO,
    val BLC: BLC,
    val BLOCK: BLOCK,
    val BLU: BLU,
    val BLZ: BLZ,
    val BMC: BMC,
    val BNB: BNB,
    val BNT: BNT,
    val BOST: BOST,
    val BQ: BQ,
    val BQX: BQX,
    val BRD: BRD,
    val BRIT: BRIT,
    val BT1: BT1,
    val BT2: BT1,
    val BTC: BTC,
    val BTCA: BTCA,
    val BTCS: BTCS,
    val BTCZ: BTCZ,
    val BTG: BTG,
    val BTLC: BTLC,
    val BTM: BTM,
   // val BTMX: BTMX,
    val BTQ: BTQ,
    val BTS: BTS,
    val BTX: BTX,
    val BURST: BURST,
    val CALC: CALC,
    val CAS: CAS,
    val CAT: CAT,
    val CCRB: CCRB,
    val CDT: CDT,
    val CESC: CESC,
    val CHAT: CHAT,
    val CJ: CJ,
    val CL: CL,
    val CLD: CLD,
    val CLOAK: CLOAK,
    val CMT: CMT,
    val CND: CND,
    val CNX: CNX,
    val CPC: CPC,
    val CRAVE: CRAVE,
    val CRC: CRC,
    val CRE: CRE,
    val CRW: CRW,
    val CTO: CTO,
    val CTR: CTR,
    val CVC: CVC,
    val DAS: DAS,
    val DASH: DASH,
    val DAT: DAT,
    val DATA: DATA,
    val DBC: DBC,
    val DBET: DBET,
    val DCN: DCN,
    val DCR: DCR,
    val DCT: DCT,
    val DEEP: DEEP,
    val DENT: DENT,
    val DGB: DGB,
    val DGD: DGD,
    val DIM: DIM,
    val DIME: DIME,
    val DMD: DMD,
    val DNT: DNT,
    val DOGE: DOGE,
    val DRGN: DRGN,
    val DRZ: DRZ,
    val DSH: DSH,
    val DTA: DTA,
    val EC: EC,
//    val EDG: EDG,
//    val EDO: EDO,
//    val EDR: EDR,
//    val EKO: EKO,
//    val ELA: ELA,
//    val ELF: ELF,
//    val EMC: EMC,
//    val EMGO: EMGO,
//    val ENG: ENG,
//    val ENJ: ENJ,
//    val EOS: EOS,
//    val ERT: ERT,
//    val ETC: ETC,
//    val ETH: ETH,
//    val ETN: ETN,
//    val ETP: ETP,
//    val ETT: ETT,
//    val EVR: EVR,
//    val EVX: EVX,
//    val FCT: FCT,
//    val FLP: FLP,
//    val FOTA: FOTA,
//    val FRST: FRST,
//    val FUEL: FUEL,
//    val FUN: FUN,
//    val FUNC: FUNC,
//    val FUTC: FUTC,
//    val GAME: GAME,
//    val GAS: GAS,
//    val GBYTE: GBYTE,
//    val GMX: GMX,
//    val GNO: GNO,
//    val GNT: GNT,
//    val GNX: GNX,
//    val GRC: GRC,
//    val GRS: GRS,
//    val GRWI: GRWI,
//    val GTC: GTC,
//    val GTO: GTO,
//    val GUP: GUP,
//    val GVT: GVT,
//    val GXS: GXS,
//    val HAC: HAC,
//    val HNC: HNC,
//    val HSR: HSR,
//    val HST: HST,
//    val HVN: HVN,
//    val ICN: ICN,
//    val ICOS: ICOS,
//    val ICX: ICX,
//    val IGNIS: IGNIS,
//    val ILC: ILC,
//    val INK: INK,
//    val INS: INS,
//    val INSN: INSN,
//    val INT: INT,
//    val IOP: IOP,
//    val IOST: IOST,
//    val ITC: ITC,
//    val KCS: KCS,
//    val KICK: KICK,
//    val KIN: KIN,
//    val KLC: KLC,
//    val KMD: KMD,
//    val KNC: KNC,
//    val KRB: KRB,
//    val LA: LA,
//    val LEND: LEND,
//    val LEO: LEO,
//    val LINDA: LINDA,
//    val LINK: LINK,
//    val LOC: LOC,
//    val LOG: LOG,
//    val LRC: LRC,
//    val LSK: LSK,
//    val LTC: LTC,
//    val LUN: LUN,
//    val LUX: LUX,
//    val MAID: MAID,
//    val MANA: MANA,
//    val MCAP: MCAP,
//    val MCO: MCO,
//    val MDA: MDA,
//    val MDS: MDS,
//    val MIOTA: MIOTA,
//    val MKR: MKR,
//    val MLN: MLN,
//    val MNX: MNX,
//    val MOD: MOD,
//    val MOIN: MOIN,
//    val MONA: MONA,
//    val MTL: MTL,
//    val MTN*: MTN,
//    val MTX: MTX,
//    val NAS: NAS,
//    val NAV: NAV,
//    val NBT: NBT,
//    val NDC: NDC,
//    val NEBL: NEBL,
//    val NEO: NEO,
//    val NEU: NEU,
//    val NEWB: NEWB,
//    val NGC: NGC,
//    val NKC: NKC,
//    val NLC2: NLC2,
//    val NMC: NMC,
//    val NMR: NMR,
//    val NULS: NULS,
//    val NVC: NVC,
//    val NXT: NXT,
//    val OAX: OAX,
//    val OBITS: OBITS,
//    val OC: OC,
//    val OCN: OCN,
//    val ODN: ODN,
//    val OK: OK,
//    val OMG: OMG,
//    val OMNI: OMNI,
//    val ORE: ORE,
//    val ORME: ORME,
//    val OST: OST,
//    val OTN: OTN,
//    val OTX: OTX,
//    val OXY: OXY,
//    val PART: PART,
//    val PAY: PAY,
//    val PBT: PBT,
//    val PCS: PCS,
//    val PIVX: PIVX,
//    val PIZZA: PIZZA,
//    val PLBT: PLBT,
//    val PLR: PLR,
//    val POE: POE,
//    val POLY: POLY,
//    val POSW: POSW,
//    val POWR: POWR,
//    val PPC: PPC,
//    val PPT: PPT,
//    val PPY: PPY,
//    val PRC: PRC,
//    val PRES: PRES,
//    val PRG: PRG,
//    val PRL: PRL,
//    val PRO: PRO,
//    val PURA: PURA,
//    val PUT: PUT,
//    val QASH: QASH,
//    val QAU: QAU,
//    val QSP: QSP,
//    val QTUM: QTUM,
//    val QUN: QUN,
//    val R: R,
//    val RBIES: RBIES,
//    val RCN: RCN,
//    val RDD: RDD,
//    val RDN: RDN,
//    val RDN*: RDNX,
//    val REBL: REBL,
//    val REE: REE,
//    val REP: REP,
//    val REQ: REQ,
//    val REV: REV,
//    val RGC: RGC,
//    val RHOC: RHOC,
//    val RIYA: RIYA,
//    val RKC: RKC,
//    val RLC: RLC,
//    val RPX: RPX,
//    val RUFF: RUFF,
//    val SALT: SALT,
//    val SAN: SAN,
//    val SBC: SBC,
//    val SC: SC,
//    val SENT: SENT,
//    val SHIFT: SHIFT,
//    val SIB: SIB,
//    val SMART: SMART,
//    val SMLY: SMLY,
//    val SMT*: SMT,
//    val SNC: SNC,
//    val SNGLS: SNGLS,
//    val SNM: SNM,
//    val SNT: SNT,
//    val SPK: SPK,
//    val SRN: SRN,
//    val STEEM: STEEM,
//    val STK: STK,
//    val STORJ: STORJ,
//    val STRAT: STRAT,
//    val STU: STU,
//    val STX: STX,
//    val SUB: SUB,
//    val SUR: SUR,
//    val SWFTC: SWFTC,
//    val SYS: SYS,
//    val TAAS: TAAS,
//    val TESLA: TESLA,
//    val THC: THC,
//    val THETA: THETA,
//    val THS: THS,
//    val TIO: TIO,
//    val TKN: TKN,
//    val TKY: TKY,
//    val TNB: TNB,
//    val TNT: TNT,
//    val TOA: TOA,
//    val TRC: TRC,
//    val TRIG: TRIG,
//    val TRST: TRST,
//    val TRUMP: TRUMP,
//    val TRX: TRX,
//    val UBQ: UBQ,
//    val UNO: UNO,
//    val UNRC: UNRC,
//    val UQC: UQC,
//    val USDT: USDT,
//    val UTK: UTK,
//    val UTT: UTT,
//    val VEE: VEE,
//    val VEN: VEN,
//    val VERI: VERI,
//    val VIA: VIA,
//    val VIB: VIB,
//    val VIBE: VIBE,
//    val VOISE: VOISE,
//    val VOX: VOX,
//    val VRS: VRS,
//    val VTC: VTC,
//    val VUC: VUC,
//    val WABI: WABI,
//    val WAVES: WAVES,
//    val WAX: WAX,
//    val WC: WC,
//    val WGR: WGR,
//    val WINGS: WINGS,
//    val WLK: WLK,
//    val WOP: WOP,
//    val WPR: WPR,
//    val WRC: WRC,
//    val WTC: WTC,
//    val XAUR: XAUR,
//    val XBP: XBP,
//    val XBY: XBY,
//    val XCP: XCP,
//    val XCXT: XCXT,
//    val XDN: XDN,
//    val XEM: XEM,
//    val XGB: XGB,
//    val XHI: XHI,
//    val XID: XID,
//    val XLM: XLM,
//    val XMR: XMR,
//    val XNC: XNC,
//    val XRB: XRB,
//    val XRP: XRP,
//    val XTO: XTO,
//    val XTZ: XTZ,
//    val XUC: XUC,
//    val XVG: XVG,
//    val XZC: XZC,
//    val YEE: YEE,
//    val YOC: YOC,
//    val YOYOW: YOYOW,
//    val ZBC: ZBC,
//    val ZCL: ZCL,
//    val ZEC: ZEC,
//    val ZEN: ZEN,
//    val ZIL: ZIL,
//    val ZNY: ZNY,
//    val ZRX: ZRX,
//    val ZSC: ZSC
)